
debug:
	g++ --std=c++17  expressionMatchSingle.cpp  main.cpp -o regex.out 
	./regex.out --debug > basic.log

release:
	g++ --std=c++17 expressionMatchSingle.cpp main.cpp -o regex.out
	./regex.out > basic.log

#make for test as well
